### ISSUE TITLE
master branch does not compile on ubuntu 16.04 because pthread not linked in LogisticRegression Application

### ISSUE THREAD

**Issue by NicolasWinckler** [Microsoft/Multiverso#130]
Hello,

The multiverso does not compile on my ubuntu. I had the following error:
/usr/bin/ld: CMakeFiles/LogisticRegression.dir/src/reader.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line

I could fix the issue by adding the missing pthread in https://github.com/Microsoft/Multiverso/blob/master/Applications/LogisticRegression/CMakeLists.txt as follow: 

target_link_libraries(LogisticRegression multiverso ${MPI_CXX_LIBRARIES} pthread)

I am working on a linux machine with the following characteristics:
Distributor ID: Ubuntu
Description: Ubuntu 16.04.1 LTS
Release: 16.04
Codename: xenial

my gcc is gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609

**Comment by chivee** [comment]
#131 has solved this issues
